app_api/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('all/<str:response_type>', views.contacts, name='contacts'),
	path('directions/', views.directions, name='directions'),
	path('contact_list/', views.ContactList.as_view()),
	path('contact_detail/<int:pk>', views.ContactDetail.as_view()),
	path('user_list/', views.UserList.as_view())
]

app_users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'users'
urlpatterns = [
	path('login/', views.LoginView.as_view(), name='login'),
	path('logout/', views.LogoutView.as_view(), name='logout'),
	path('registration/', views.RegistrationView.as_view(), name='registration'),
	path('manage/', login_required( views.ManageView.as_view() ), name='manage'),
	path('manage_personal_details/', login_required( views.ManagePersonalDetailsView.as_view() ), name='manage_personal_details'),
	path('change_user_password/', login_required( views.ChangeUserPasswordView.as_view() ), name='change_user_password'),
]

project/urls.py
from django.urls import include,path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from rest_framework import routers
from app_api import views 

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'usersapi', views.UserViewSet)
router.register(r'contactsapi', views.ContactViewSet)

#handler404 = 'app_homepage.views.showError404'
#handler500 = 'app_homepage.views.showError500'

urlpatterns = [
    path('api/', include(router.urls)),   
    path('api/', include('app_api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('home/', include('app_homepage.urls')),
    path('users/', include('app_users.urls')),
    path('captcha/', include('captcha.urls')), 
    path('contacts/', include('app_contacts.urls')),
    path('password_reset_recover/', include('password_reset.urls')),  
    path('geodjango/', include('app_geodjango.urls')),
    path('tasks/', include('app_tasks.urls')),
    path('chat/', include('app_chat.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^.*', TemplateView.as_view(template_name='react.html')),
    
] 

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.http import HttpResponse
from captcha.fields import CaptchaField
from django.template.defaultfilters import filesizeformat
from django.conf import settings


class LoginForm(forms.Form):
    username = forms.CharField(max_length = 50)
    password = forms.CharField(max_length = 50, widget=forms.PasswordInput)
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput())

    # Constructor ( Override default constructor )
    def __init__(self, *args, **kwargs):

        # pop out the request object and add it as an instance attribute
        self.request = kwargs.pop('request', None)

        # now call the parent constructor
        super(LoginForm, self).__init__(*args, **kwargs)


    def clean_remember_me(self):
        if not self.cleaned_data.get('remember_me'):
            self.request.session.set_expiry(0)


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length = 50,min_length = 6)
    password = forms.CharField(max_length = 50,min_length = 6)
    conf_password = forms.CharField(max_length = 50,min_length = 6)
    firstname = forms.CharField(max_length = 50)
    middlename = forms.CharField(max_length = 50, required = False)
    lastname = forms.CharField(max_length = 50)
    email = forms.EmailField(max_length = 50)
    phone = forms.CharField(max_length = 50, required = False)
    photo = forms.FileField(allow_empty_file = True,required = False)
    captcha = CaptchaField()


    # validate unique username
    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))


    # validate confirmed password. Always use fields below(later) to validate fields above(earlier)
    def clean_conf_password(self):
        if self.cleaned_data['password'] != self.cleaned_data['conf_password']:            
            raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data['conf_password']


    # validate unique email
    def clean_email(self):
        try:
            user = User.objects.get(email__iexact=self.cleaned_data['email'])
        except User.DoesNotExist:
            return self.cleaned_data['email']
        raise forms.ValidationError(_("The email already exists. Please try another one."))


    # validate the photo field
    def clean_photo(self):
        photo = self.cleaned_data['photo']
        # raise forms.ValidationError(_(photo.content_type.split('/')[1]))
        if hasattr(photo, 'content_type'):           
            content_type = photo.content_type.split('/')[1]
            if content_type in settings.CONTENT_TYPES:
                if photo.size > settings.MAX_UPLOAD_SIZE:
                    raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(photo._size)))
            else:
                raise forms.ValidationError(_('File type is not supported'))
            return photo
        return photo


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(max_length = 50, min_length = 6, widget = forms.PasswordInput)
    new_password = forms.CharField(max_length = 50, min_length = 6, widget = forms.PasswordInput)
    conf_password = forms.CharField(max_length = 50, min_length = 6, widget = forms.PasswordInput)    

    # Constructor ( Override default constructor )
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ChangePasswordForm, self).__init__(*args, **kwargs)


    # validate current password.
    def clean_current_password(self):
        user = self.request.user
        current_password = self.cleaned_data['current_password']

        if not user.check_password(current_password):
            raise forms.ValidationError(_("The current password is incorrect."))
        return self.cleaned_data['current_password']   


    # validate confirmed password. Always use fields below(later) to validate fields above(earlier)
    def clean_conf_password(self):
        if self.cleaned_data['new_password'] != self.cleaned_data['conf_password']:            
            raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data['conf_password']


class PersonalDetailsForm(forms.Form):
    firstname = forms.CharField(max_length = 50)
    middlename = forms.CharField(max_length = 50, required = False)
    lastname = forms.CharField(max_length = 50)
    email = forms.EmailField(max_length = 50)
    phone = forms.CharField(max_length = 50, required = False)
    photo = forms.FileField(allow_empty_file = True,required = False)

    # Constructor ( Override default constructor )
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(PersonalDetailsForm, self).__init__(*args, **kwargs)


    # validate unique email
    def clean_email(self):
        user = self.request.user

        if User.objects.filter(email__iexact=self.cleaned_data['email']).exists():
            retrieved_user = User.objects.filter(email__iexact=self.cleaned_data['email'])[0]

            if retrieved_user:
                if retrieved_user.id != user.id:
                    # The email belongs to someone other than the logged_in user
                    raise forms.ValidationError(_("The email already exists. Please try another one."))
                return self.cleaned_data['email']
        return self.cleaned_data['email']


    # validate the photo field
    def clean_photo(self):
        photofield = self.cleaned_data['photo']

        if hasattr(photofield, 'content_type'):           
            content_type = photofield.content_type.split('/')[1]
            if content_type in settings.CONTENT_TYPES:
                if photofield.size > settings.MAX_UPLOAD_SIZE:
                    raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(photo._size)))
            else:
                raise forms.ValidationError(_('File type is not supported'))
        return photofield

app_users/views.py
import datetime,os,shutil
import pdb,pprint

from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib.auth import authenticate, login,logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render,get_object_or_404
from django.views.generic import View
from . forms import LoginForm,RegistrationForm,ChangePasswordForm,PersonalDetailsForm,User # the dot means "this current directory"
from django.conf import settings
from django.contrib.auth.models import Group
from django.utils.decorators import method_decorator
from django.contrib import messages




# # test admin  @user_passes_test(is_admin)
# def is_admin(user):
#     return user.groups.filter(name='admin').exists()

# def is_logged_in(user):
#     return user.is_authenticated

# # -------This decorator will apply to all views in this class------
# @method_decorator(user_passes_test(is_logged_in))
# def dispatch(self, *args, **kwargs):
#     return super(ManageView, self).dispatch(*args, **kwargs)
# # ------------------------------------------------------------------


class LoginView(View):
    def get(self,request):  
        return render(request, 'app_users/login.html')


    def post(self,request):

        #pdb.set_trace()

    	# create a form instance and populate it with data from the request:
        form = LoginForm(request.POST,request = request)
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:

            # get username and password
            username,password = form.cleaned_data['username'],form.cleaned_data['password']

            # authenticate user
            user = authenticate(username=username, password=password)
            
            if user is not None:
                if user.is_active:
                    login(request,user) 
                    return HttpResponseRedirect('/')
                else:
                    messages.add_message(request, messages.ERROR, "Sorry, this user is inactive")
                    return render(request, 'app_users/public_login.html', {'loginform': form})
            else:
                messages.add_message(request, messages.ERROR, "invalid credentials or inactive user")
                return render(request, 'app_users/login.html', {'loginform': form})
            return HttpResponseRedirect('/')
        else:
        	return render(request, 'app_users/login.html', {'loginform': form})


class LogoutView(View):
    def get(self,request):
        logout(request)
        messages.add_message(request, messages.SUCCESS, "You are now logged out")
        return HttpResponseRedirect('/users/login')


class RegistrationView(View):
    def get(self,request): 

        #we need to pass an empty form because of the captcha field
        form = RegistrationForm()
        return render(request, 'app_users/register.html', {'emptyForm':form})

    
    def post(self,request):
        
        # create a form instance and bind it with the request data:
        form = RegistrationForm(request.POST,request.FILES)
        
        if form.is_valid():

            # creating new user object
            user = User.objects.create_user(                
                username = form.cleaned_data['username'],
                email = form.cleaned_data['email'],
                password = form.cleaned_data['password'],
            )

            # update user data
            user.first_name = form.cleaned_data['firstname']
            user.last_name = form.cleaned_data['lastname']
            user.last_login = datetime.datetime.now()
            user.date_joined = datetime.datetime.now()
            user.is_superuser = False
            user.is_staff = True
            user.is_active = True
            

            # save the user
            user.save()

            # add user to the public group if only it exists
            if Group.objects.filter(name='public').exists():
                g = Group.objects.filter(name='public')
                g.user_set.add(user)


            # extended profile attributes
            user_profile = user.profile
            user_profile.middlename = form.cleaned_data['middlename']
            user_profile.phone = form.cleaned_data['phone']
            user_profile.photo = request.FILES['photo'] if 'photo' in request.FILES else None
            user_profile.save()

            messages.add_message(request, messages.SUCCESS, "Registration Successful. Your account has now been created")
            
            return HttpResponseRedirect('/')
        else:
            return render(request, 'app_users/register.html', {'regform': form})


class ManageView(View):
    def get(self,request):
        return render(request, 'app_users/manage.html')


class ChangeUserPasswordView(View):
    def get(self,request):

        data = {'show_change_password':True}
        return render(request, 'app_users/manage.html', data)


    def post(self,request):

        # create a form instance and bind it with the request data:
        form = ChangePasswordForm(request.POST,request = request)

        if form.is_valid():

            new_password = form.cleaned_data['new_password']
            user = request.user
            username = user.username
            user.set_password(new_password)
            user.save()

            # NB! set_password will logout user when it is successful
            # hence, Re-authenticate the user with new_password and log them in
            user = authenticate(username=username, password=new_password)
            login(request, user) 

            # return to change password page with success message
            messages.add_message(request, messages.SUCCESS, "Password was changed Successfully")
            return HttpResponseRedirect('/users/manage/')

        else:
            return render(request, 'app_users/manage.html', {'show_change_password':True,'change_password_form':form})


class ManagePersonalDetailsView(View):
    def get(self,request):
        
        user = request.user
        user_profile = user.profile

        initial_data = {
            'firstname' : user.first_name,
            'middlename' : user_profile.middlename,
            'lastname' : user.last_name,
            'email' : user.email,
            'phone' : user_profile.phone
        }

        #we need to pass an empty form because of the captcha field
        form = PersonalDetailsForm(initial = initial_data)
        data = {'form':form,'show_personal_details':True}

        return render(request, 'app_users/manage.html', data)

    def post(self,request):

        # create a form instance and bind it with the request data:
        form = PersonalDetailsForm(request.POST,request.FILES,request = request)
        
        if form.is_valid():

            # get the user object
            user = request.user
            user.first_name = form.cleaned_data['firstname']
            user.last_name = form.cleaned_data['lastname']
            user.email = form.cleaned_data['email']
            

            # get the existing user profile data
            user_profile = user.profile
            old_photo_filename = user_profile.photo.name
            user_profile.middlename = form.cleaned_data['middlename']
            user_profile.phone = form.cleaned_data['phone']
            if 'photo' in request.FILES:
                user_profile.photo = request.FILES['photo']
                user_profile.hasPhotoUpload = True
            else:
                user_profile.hasPhotoUpload = False
            

            # Save all changes
            user.save()      
            user_profile.save()

            messages.add_message(request, messages.SUCCESS, 'Updated Successfully')

            return HttpResponseRedirect('/users/manage/')
            
        else:
            return render(request, 'app_users/manage.html', {'form': form,'show_personal_details':True})

app_users/templates/app_users/change_user_password.html
 <h2 style="color: rgba(149, 149, 149, 0.80);">Change Password</h2>
 <i>(Note. All fields tagged with a star symbol(*) are strictly required)</i>
 <br/><br/>

<form method="post" action="{% url 'users:change_user_password' %}">
{% csrf_token %}

<div class="row">
    <div class="col-sm-5">

    Current Password*:<br />
    <input type="password" name="current_password" value="{{ change_password_form.current_password.value }}" class="form-control" placeholder="Your original password" />
    <small class="alert-danger">{{ change_password_form.current_password.errors }}</small><br />

    New Password*:<br />
    <input type="password" name="new_password" value="{{ change_password_form.new_password.value }}" class="form-control" placeholder="Your new password" />
    <small class="alert-danger">{{ change_password_form.new_password.errors }}</small><br />

    Comfirm New Password*:<br />
    <input type="password" name="conf_password" value="{{ change_password_form.conf_password.value }}" class="form-control" placeholder="Repeat your new password" />
    <small class="alert-danger">{{ change_password_form.conf_password.errors }}</small><br />

    </div>

    <span class="clearfix"></span>
    <hr />
    <input class="btn btn-sm btn-primary" type="submit" value="Submit" name="submit" />
</div>
</form>

app_users/templates/app_users/login.html
{% extends "layout/master.html" %}
{% load static %}
{% block title %}Login{% endblock %}

{% block content %}

{{ form.non_field_errors }}
<div class="col-sm-6">
	<h2>Login</h2><hr/>

    <!--Show notification/error messages here -->
	{% if messages %}
		{% include "layout/messages.html" %}
	{% endif %}

	<form method="post" action="{% url 'users:login' %}">
	{% csrf_token %}
		
		Username/Email:<br />
		<input type="text" name="username" value="{{ loginform.username.value }}" class="form-control" />
		<small class="alert-danger">{{ loginform.username.errors }}</small>

		Password:<br />
		<input type="password" name="password" value="{{ loginform.password.value }}" class="form-control" />
		<small class="alert-danger">{{ loginform.password.errors }} </small>

		<!--Forgot password-->
		<div>
			<a href="{% url 'password_reset_recover' %}">Forgot Password</a>
		</div>
		<br />

		<!--remember me-->
		<div><input name="remember_me" type="checkbox"/> Remember Me</div>
		<br/>

    	<input class="btn btn-sm btn-primary" type="submit" value="Login" name="login" />
	</form>
</div>
{% endblock %}

app_users/templates/app_users/manage.html
{% extends "layout/master.html" %}
{% load staticfiles %}
{% block title %}Manage Account{% endblock %}

{% block content %}
<div id="my-account-page">

    <h2>My Account</h2>
    <hr/>

    <div align="center">
        <a href="{% url 'users:manage_personal_details' %}" class='btn btn-sm btn-default'>Personal Details</a>
        <a href="{% url 'users:change_user_password' %}" class='btn btn-sm btn-default'>Change Password</a>
    </div>
    <hr/>

    <div>

        <!--Show alert messages here -->
        {% if messages %}
            {% include "layout/messages.html" %}
        {% endif %}


        <!--Show dynamic info here -->
        {% if show_personal_details %}
            {% include "app_users/manage_personal_details.html" %}
        {% elif show_change_password %}
            {% include "app_users/change_user_password.html" %}
        {% endif %}

    </div>

</div>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript" src="{% static 'app_users/js/app.js' %}" ></script>
{% endblock %}

app_users/templates/app_users/manage_personal_details.html
{% load static %}

<h2 style="color: rgba(149, 149, 149, 0.80);">Manage Personal Details</h2>
<i>(Note. All fields tagged with a star symbol(*) are strictly required)</i>
<br/><br/>


<!--Show notification/error messages here -->
{% if messages %}
    {% include "layout/messages.html" %}
{% endif %}
 
<form enctype="multipart/form-data" method="post" action="{% url 'users:manage_personal_details' %}">
{% csrf_token %}

<div class="row">           
    <div class="col-sm-5">

        <!--Firstname-->
        <div class="form-group">
            <label for="firstname">Firstname*</label>
            <input type="text" name="firstname" size="50" maxlength="30" class="form-control" value="{{ form.firstname.value }}"  >
            <small class="alert-danger">{{ form.firstname.errors }}</small>
        </div>

        <!--Middlename-->
        <div class="form-group">
            <label for="middlename">Middlename</label>
            <input type="text" name="middlename" size="50" maxlength="30" class="form-control" value="{{ form.middlename.value }}"  >
            <small class="alert-danger">{{ form.middlename.errors }}</small>
        </div>

        <!--Lastname-->
        <div class="form-group">
            <label for="lastname">Lastname*</label>
            <input type="text" name="lastname" size="50" maxlength="30" class="form-control" value="{{ form.lastname.value }}"  >
            <small class="alert-danger">{{ form.lastname.errors }}</small>
        </div>


        <!--Email-->
        <div class="form-group">
            <label for="email">Email*</label>
            <input type="text" name="email" size="50" maxlength="30" class="form-control" value="{{ form.email.value }}"  >
            <small class="alert-danger">{{ form.email.errors }}</small>
        </div>


        <!--Phone-->
        <div class="form-group">
            <label for="phone">Phone #</label>
            <input type="text" name="phone" size="50" maxlength="30" class="form-control" value="{{ form.phone.value }}"  >
            <small class="alert-danger">{{ form.phone.errors }}</small>
        </div>

    </div>

    <div class="col-sm-5">

        <!--upload photo-->
        <div class="form-group">
            <label for="photo">Upload Photo (5Mb Max) </label>              
            {% if form.photo %}{{ form.photo }}{% else %}{{ form.photo }}{% endif %}
            <div class="img-container">
                <img id="userPhoto2" class="img-rounded img-responsive" alt="photo" src="/media/img/{{user.profile.photo.name}}" />

                <span class="btn btn-default btn-sm clrPhoto">Clear Photo</span>
                <small class="alert-danger">{{ form.photo.errors }}</small>
            </div>
        </div>
    </div>

    <span class="clearfix"></span>

    <hr/>
    <input class="btn btn-sm btn-primary" type="submit" value="Update" name="submit" />   
</div>
</form>

app_users/templates/app_users/register.html
{% extends "layout/master.html" %}
{% load static %}
{% block title %}Registration{% endblock %}


{% block extra_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'app_users/css/app.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app_users/css/tablet_and_up.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app_users/css/desktop_and_up.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app_users/css/large_desktops_and_up.css' %}" />
{% endblock %}

{% block content %}

{{ form.non_field_errors }}
<div class="col-sm-8">


 <h2>Register</h2>
 <i>(Note. All fields tagged with a star symbol(*) are strictly required)</i>
 <hr />

<!--Show notification/error messages here -->
{% if messages %}
    {% include "layout/messages.html" %}
{% endif %}


<form class="row" enctype="multipart/form-data" method="post" action="{% url 'users:registration' %}">
{% csrf_token %}

	<div class="col-sm-6">

		<!--Username-->
		<div class="form-group">
			<label for="username">Username*</label>
			<input type="text" name="username" size="50" maxlength="30" class="form-control" value="{{ regform.username.value }}"  >
			<small class="alert-danger">{{ regform.username.errors }}</small>
		</div>

		<!--Password-->
		<div class="form-group">
			<label for="password">Password*</label>
			<input type="password"  name="password" size="50" maxlength="30" class="form-control" value="{{ regform.password.value }}" >
			<small class="alert-danger">{{ regform.password.errors }}</small>
		</div>

		<!--Password Confirmation-->
		<div class="form-group">
			<label for="conf_password">Confirm Password*</label>
			<input type="password" name="conf_password" size="50" maxlength="30" class="form-control" value="{{ regform.conf_password.value }}"  >
			<small class="alert-danger">{{ regform.conf_password.errors }}</small>
		</div>

		<!--Firstname-->
		<div class="form-group">
			<label for="firstname">Firstname*</label>
			<input type="text" name="firstname" size="50" maxlength="30" class="form-control" value="{{ regform.firstname.value }}"  >
			<small class="alert-danger">{{ regform.firstname.errors }}</small>
		</div>

		<!--Middlename-->
		<div class="form-group">
			<label for="middlename">Middlename</label>
			<input type="text" name="middlename" size="50" maxlength="30" class="form-control" value="{{ regform.middlename.value }}"  >
			<small class="alert-danger">{{ regform.middlename.errors }}</small>
		</div>

		<!--Lastname-->
		<div class="form-group">
			<label for="lastname">Lastname*</label>
			<input type="text" name="lastname" size="50" maxlength="30" class="form-control" value="{{ regform.lastname.value }}"  >
			<small class="alert-danger">{{ regform.lastname.errors }}</small>
		</div>

	</div>

	<div class="col-sm-6">

		<!--Email-->
		<div class="form-group">
			<label for="email">Email*</label>
			<input type="text" name="email" size="50" maxlength="30" class="form-control" value="{{ regform.email.value }}"  >
			<small class="alert-danger">{{ regform.email.errors }}</small>
		</div>

		<!--Phone-->
		<div class="form-group">
			<label for="phone">Phone #</label>
			<input type="text" name="phone" size="50" maxlength="30" class="form-control" value="{{ regform.phone.value }}"  >
			<small class="alert-danger">{{ regform.phone.errors }}</small>
		</div>

		<!--upload photo-->
		<div class="form-group">
			<label for="photo">Upload Photo (5Mb Max) </label>				
			{% if emptyForm.photo %}{{ emptyForm.photo }}{% else %}{{ regform.photo }}{% endif %}
			<div class="img-container">
				<img id="userPhoto" class="img-rounded img-responsive" alt="photo" src="{% static "app_users/img/usericon.svg" %}" />

				<span class="btn btn-default btn-sm clrPhoto">Clear Photo</span>
				<small class="alert-danger">{{ regform.photo.errors }}</small>
			</div>
		</div>
		<br/>

		<!--Captcha-->
		<div class="form-group">
			<fieldset>
				<legend>Enter image contents below*</legend>
				{% if emptyForm.captcha %}{{ emptyForm.captcha }}{% else %}{{ regform.captcha }}{% endif %}
				<span class="btn btn-default btn-sm js-captcha-refresh">
					<span class="glyphicon glyphicon-refresh"> Refresh</span> 
				</span>
				
				<small class="alert-danger">{{ regform.captcha.errors }}</small>
			</fieldset>
		</div>
	</div>


	<span class="clearfix"></span>
    <hr />
	<input class="btn btn-primary" type="submit" value="Register" name="register" />

</form>


</div>
{% endblock %}


{% block extra_scripts %}
<script type="text/javascript" src="{% static 'app_users/js/app.js' %}" ></script>
{% endblock %}