app_api/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('all/<str:response_type>', views.contacts, name='contacts'),
	path('directions/', views.directions, name='directions'),
	path('contact_list/', views.ContactList.as_view()),
	path('contact_detail/<int:pk>', views.ContactDetail.as_view()),
	path('user_list/', views.UserList.as_view())
]

app_contacts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'contacts'
urlpatterns = [
	path('index/', login_required( views.IndexView.as_view() ), name='index'),
	path('add/', login_required( views.AddView.as_view() ), name='add'),
	path('edit/<int:pk>', login_required(views.EditView.as_view() ), name='edit'),
	path('delete/<int:pk>', login_required(views.DeleteView.as_view() ), name='delete'),
	path('sendmail/<int:pk>', login_required( views.EmailView.as_view() ), name='sendmail'),
	path('report/', login_required( views.ReportView ), name='report'),
]

project/urls.py
from django.urls import include,path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from rest_framework import routers
from app_api import views 

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'usersapi', views.UserViewSet)
router.register(r'contactsapi', views.ContactViewSet)

#handler404 = 'app_homepage.views.showError404'
#handler500 = 'app_homepage.views.showError500'

urlpatterns = [
    path('api/', include(router.urls)),   
    path('api/', include('app_api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('home/', include('app_homepage.urls')),
    path('users/', include('app_users.urls')),
    path('captcha/', include('captcha.urls')), 
    path('contacts/', include('app_contacts.urls')),
    path('password_reset_recover/', include('password_reset.urls')),  
    path('geodjango/', include('app_geodjango.urls')),
    path('tasks/', include('app_tasks.urls')),
    path('chat/', include('app_chat.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^.*', TemplateView.as_view(template_name='react.html')),
    
] 

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_contacts/models.py
from django.db import models
from django.contrib.auth.models import User

class Contact(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE) # required
	firstname = models.CharField(max_length = 50) # required
	middlename = models.CharField(max_length = 50, blank=True, null=True)
	lastname = models.CharField(max_length = 50) # required
	email = models.EmailField(max_length = 50) # required
	tel1 = models.CharField(max_length = 50) # required
	tel2 = models.CharField(max_length = 50, blank=True, null=True)

	def __str__(self):
		return '%s %s %s' % (self.firstname, self.middlename, self.lastname)

	class Meta:
		db_table = 'contacts'

app_contacts/forms.py
from django import forms
from django.forms import ModelForm
from . models import Contact
from django.utils.translation import gettext as _

class ContactForm(ModelForm):
	class Meta:
		model = Contact
		fields = ['firstname','middlename','lastname','email','tel1','tel2']
		#exclude = ['user_id']


	def clean_tel1(self):
		tel1 = self.cleaned_data['tel1']
		if not tel1.isdigit():
			raise forms.ValidationError(_("This field must be numeric"))
		return self.cleaned_data['tel1']


	def clean_tel2(self):
		tel2 = self.cleaned_data['tel2']
		if tel2 is not None:
			if not tel2.isdigit():
				raise forms.ValidationError(_("This field must be numeric %s" % tel2))			
		return self.cleaned_data['tel2']


class EmailForm(forms.Form):
    subject = forms.CharField(max_length = 50)
    message = forms.CharField(max_length = 1000)
    recipient = forms.EmailField(max_length = 50)

app_contacts/views.py
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.contrib.auth.decorators import login_required,permission_required,user_passes_test
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render,get_object_or_404
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.core.mail import send_mail,EmailMessage
from django.template.loader import get_template
from django.template import Context
from . forms import ContactForm,EmailForm
from . models import Contact
from xhtml2pdf import pisa
import datetime
import os
from pprint import pprint
from django.conf import settings
from django.core.files.storage import default_storage
from django.contrib import messages


class IndexView(View):
	
	def get(self, request):

		# function level authorization
		if(request.user.has_perm('app_contacts.view_contact') == False):
			referer = request.META['HTTP_REFERER']
			return HttpResponse("<h4>Sorry, you don't have permission to view. <a href=%s>Return</a></h4>" % referer )

		# get all contacts for this user
		contacts = request.user.contact_set.all()
		data = {'contacts':contacts}
		return render(request, 'app_contacts/index.html', data)


class AddView(View):

	def get(self, request):
		if(request.user.has_perm('app_contacts.add_contact') == False):
			referer = request.META['HTTP_REFERER']
			return HttpResponse("<h4>Sorry, you don't have permission to add. <a href=%s>Return</a></h4>" % referer )

		return render(request, 'app_contacts/add.html')

	def post(self,request):
		if(request.user.has_perm('app_contacts.add_contact') == False):
			referer = request.META['HTTP_REFERER']
			return HttpResponse("<h4>Sorry, you don't have permission to add. <a href=%s>Return</a></h4>" % referer )


		ContactModel = Contact(user = request.user)
		form = ContactForm(request.POST, instance = ContactModel)

		if form.is_valid():		

			form.save()
			messages.add_message(request, messages.SUCCESS, "Contact added successfully.You may add more")
			return HttpResponseRedirect('/contacts/add')

		else:
			return render(request, 'app_contacts/add.html', {'contactform': form})


class EditView(View):
	def get(self, request, pk):

		# get the contact object from the database
		ContactModel = Contact.objects.get(pk = pk)

		# bind it to a Contact Form
		form = ContactForm(instance = ContactModel)
		

		# prepare data
		data = {'contactform':form, 'ContactID':pk}

		return render(request, 'app_contacts/edit.html',data)	

	def post(self, request, pk):
		ContactModel = Contact.objects.get(pk = pk)
		form = ContactForm(request.POST, instance = ContactModel)

		if form.is_valid():
			form.save()
			messages.add_message(request, messages.SUCCESS, "Contact updated successfully")
			return HttpResponseRedirect('/contacts/index')
		else:
			return render(request, 'app_contacts/edit.html', {'contactform': form, 'ContactID':pk})


class DeleteView(View):
	def get(self, request, pk):

		#get the contact from the database
		ContactModel = Contact.objects.get(pk = pk)

		#create a dialog
		data = {
			'dialog_title' : "Confirm Delete",
			'dialog_msg' : "Do you want to permanently delete %s?" % ContactModel,
			'action_url' : "contacts:delete",
			'args' : pk
		}
		
		#show dialog
		return render(request, 'layout/dialog.html', data)

	def post(self, request, pk):

		if request.POST['option'] == "no":
			messages.add_message(request, messages.SUCCESS, "Action was cancelled")
			return HttpResponseRedirect('/contacts/index')
		else:

			#get the contact from the database
			ContactModel = Contact.objects.get(pk = pk)

			#get contact name
			name = ContactModel.__unicode__()

			#delete the contact
			ContactModel.delete()

			#put a success message in the session
			messages.add_message(request, messages.SUCCESS, "%s was deleted successfully" % name)

			#redirect to the index page
			return HttpResponseRedirect('/contacts/index')


class EmailView(View):
	def get(self, request, pk):

		#get the contact from the database
		contact = Contact.objects.get(pk = pk)

		# show the email form
		return render(request, 'app_contacts/sendmail.html', {'contact':contact})

	def post(self, request, pk):

		# create the contact form
		form = EmailForm(request.POST)

		# get the contact from the database
		contact = Contact.objects.get(pk = pk)

		if form.is_valid():
			#send the email here

			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			recipient_email = form.cleaned_data['recipient']
			sender_email = request.user.email
			user_fullname = request.user.last_name + ' ' + request.user.first_name

			header_message = "Hello %s, your friend %s, using email %s sent you a mail through our system.Kindly read it below." % (contact,user_fullname,sender_email)
			body = header_message + '\n\n' + message 


			email = EmailMessage(subject = subject, body = body, to=[recipient_email],reply_to=[sender_email])
			email.send()

			return HttpResponse("form is valid")
		else:
			return render(request, 'app_contacts/sendmail.html', {'emailform': form, 'contact':contact})


def ReportView(request):

	today = datetime.datetime.today()
	contacts = request.user.contact_set.all()

	#request.scheme               # http or https
    #request.META['HTTP_HOST']    # example.com
    #request.path                 # /some/content/1/
	domain = request.scheme + "://" + request.META['HTTP_HOST']

	data = {'today':today, 'contacts':contacts, 'domain' : domain}

	template = get_template('app_contacts/rptAllContacts.html')
	html  = template.render(data)

	file = default_storage.open(os.path.join(settings.MEDIA_ROOT, 'files/report.pdf'), 'w+b')
	pisaStatus = pisa.CreatePDF(html.encode('utf-8'), dest=file,encoding='utf-8')

	file.seek(0)
	pdf = file.read()
	file.close() 
	os.unlink(file.name)
	           
	return HttpResponse(pdf, 'application/pdf')
	response['Content-Disposition'] = 'attachment; filename=report.pdf'

app_contacts/templates/app_contacts/add.html
{% extends "layout/master.html" %}
{% load static %}
{% block title %}Add New Contact{% endblock %}

{% block content %}

<div class="col-sm-6">

<h3>Add New Contact</h3>
<i>(Note. All fields tagged with a star symbol(*) are strictly required)</i>
<hr/>

    <!--Show notification/error messages here -->
	{% if messages %}
		{% include "layout/messages.html" %}
	{% endif %}


<form class="row" method="post" action="{% url 'contacts:add' %}">
{% csrf_token %}

	<div class="col-sm-6">	
		<!--First Name-->
		<div class="form-group">
			<label for="firstname">First Name*</label>
			<input type="text" name="firstname" size="50" maxlength="30" class="form-control" value="{{ contactform.firstname.value }}"  >
			<small class="alert-danger">{{ contactform.firstname.errors }}</small>
		</div>


		<!--Middle Name-->
		<div class="form-group">
			<label for="middlename">Middle Name</label>
			<input type="text" name="middlename" size="50" maxlength="30" class="form-control" value="{{ contactform.middlename.value }}"  >
			<small class="alert-danger">{{ contactform.middlename.errors }}</small>
		</div>


		<!--Last Name-->
		<div class="form-group">
			<label for="lastname">Last Name*</label>
			<input type="text" name="lastname" size="50" maxlength="30" class="form-control" value="{{ contactform.lastname.value }}"  >
			<small class="alert-danger">{{ contactform.lastname.errors }}</small>
		</div>
	</div>

	<div class="col-sm-6">	
		<!--Email-->
		<div class="form-group">
			<label for="email">Email</label>
			<input type="text" name="email" size="50" maxlength="30" class="form-control" value="{{ contactform.email.value }}"  >
			<small class="alert-danger">{{ contactform.email.errors }}</small>
		</div>


		<!--Tel1-->
		<div class="form-group">
			<label for="tel1">Tel1*</label>
			<input type="text" name="tel1" size="50" maxlength="30" class="form-control" value="{{ contactform.tel1.value }}"  >
			<small class="alert-danger">{{ contactform.tel1.errors }}</small>
		</div>


		<!--Tel2-->
		<div class="form-group">
			<label for="tel2">Tel2</label>
			<input type="text" name="tel2" size="50" maxlength="30" class="form-control" value="{{ contactform.tel2.value }}"  >
			<small class="alert-danger">{{ contactform.tel2.errors }}</small>
		</div>
	</div>

	<span class="clearfix"></span>
    <hr />
    <a class="btn btn-sm btn-default" href="{% url 'contacts:index' %}">Back</a>
    <button class="btn btn-sm btn-primary" type="submit">Add Contact</button>

</form>


</div>
{% endblock %}

app_contacts/templates/app_contacts/edit.html
{% extends "layout/master.html" %}
{% load static %}
{% block title %}Edit Contact{% endblock %}

{% block content %}

<div class="col-sm-6">

<h3>Edit Contact</h3>
<i>(Note. All fields tagged with a star symbol(*) are strictly required)</i>
<hr/>

    <!--Show notification/error messages here -->
	{% if messages %}
		{% include "layout/messages.html" %}
	{% endif %}


<form class="row" method="post" action="{% url 'contacts:edit' ContactID %}">
{% csrf_token %}

	<div class="col-sm-6">	
		<!--First Name-->
		<div class="form-group">
			<label for="firstname">First Name*</label>
			<input type="text" name="firstname" size="50" maxlength="30" class="form-control" value="{{ contactform.firstname.value }}"  >
			<small class="alert-danger">{{ contactform.firstname.errors }}</small>
		</div>


		<!--Middle Name-->
		<div class="form-group">
			<label for="middlename">Middle Name</label>
			<input type="text" name="middlename" size="50" maxlength="30" class="form-control" 
			value=" {% if contactform.middlename is not None %} {{contactform.middlename.value}} {% endif %} "  >
			<small class="alert-danger">{{ contactform.middlename.errors }}</small>
		</div>


		<!--Last Name-->
		<div class="form-group">
			<label for="lastname">Last Name*</label>
			<input type="text" name="lastname" size="50" maxlength="30" class="form-control" value="{{ contactform.lastname.value }}"  >
			<small class="alert-danger">{{ contactform.lastname.errors }}</small>
		</div>
	</div>

	<div class="col-sm-6">	
		<!--Email-->
		<div class="form-group">
			<label for="email">Email</label>
			<input type="text" name="email" size="50" maxlength="30" class="form-control" value="{{ contactform.email.value }}"  >
			<small class="alert-danger">{{ contactform.email.errors }}</small>
		</div>


		<!--Tel1-->
		<div class="form-group">
			<label for="tel1">Tel1*</label>
			<input type="text" name="tel1" size="50" maxlength="30" class="form-control" value="{{ contactform.tel1.value }}"  >
			<small class="alert-danger">{{ contactform.tel1.errors }}</small>
		</div>


		<!--Tel2-->
		<div class="form-group">
			<label for="tel2">Tel2</label>
			<input type="text" name="tel2" size="50" maxlength="30" class="form-control"
			value="{% if contactform.tel2.value is not None %} {{contactform.tel2.value}} {% endif %}"  >
			<small class="alert-danger">{{ contactform.tel2.errors }}</small>
		</div>
	</div>

	<span class="clearfix"></span>
    <hr />
    <a class="btn btn-sm btn-default" href="{% url 'contacts:index' %}">Back</a>
    <button class="btn btn-sm btn-primary" type="submit">Update Contact</button>

</form>


</div>
{% endblock %}

app_contacts/templates/app_contacts/index.html
{% extends "layout/master.html" %}
{% load static %}
{% block title %}All Contacts{% endblock %}

{% block extra_styles %}
<!-- data tables -->
<link rel="stylesheet" type="text/css" href="{% static 'css/dataTables/jquery.dataTables.css' %}" />
{% endblock %}


{% block content %}

<div id="all-contacts-page">

<h3>My Contacts</h3>
<hr>

  <!--Show notification/error messages here -->
  {% if messages %}
		{% include "layout/messages.html" %}
	{% endif %}

<div style="margin-bottom: 20px">
  <a href="{% url 'contacts:add' %}" class="btn btn-sm btn-primary">Add Contact</a>&nbsp;
  <a href="{% url 'contacts:report' %}" class="btn btn-sm btn-primary">PDF Report</a>&nbsp;

    <span href="#" class="dropdown">
      <a href="#" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">Export</a>

      <ul class="dropdown-menu">
          <li>
            <a onClick ="doExport({type:'csv',ignoreColumn:'[5,6,7]'});" href="#"> 
              <img src="{% static "img/tableExport/csv.png" %}" /> CSV
            </a>          
          </li>
          <li>
            <a onClick ="doExport({type:'txt'});" href="#">
              <img src="{% static "img/tableExport/txt.png" %}" /> TXT
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'json'});" href="#">
              <img src="{% static "img/tableExport/json.png" %}" /> JSON
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'json',ignoreColumn:'[5,6,7]'});" href="#">
              <img src="{% static "img/tableExport/json.png" %}" /> JSON(igonreColumn)
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'json',escape:'true'});" href="#">
              <img src="{% static "img/tableExport/json.png" %}" /> JSON(with Escape)
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'xml'});" href="#">
              <img src="{% static "img/tableExport/xml.png" %}" /> XML
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'sql'});" href="#">
              <img src="{% static "img/tableExport/sql.png" %}" /> SQL
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'excel',ignoreColumn:'[5,6,7]'});" href="#">
              <img src="{% static "img/tableExport/xls.png" %}" /> XLS
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'doc'});" href="#">
              <img src="{% static "img/tableExport/word.png" %}" /> WORD
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'png'});" href="#">
            <img src="{% static "img/tableExport/png.png" %}" />
              <?php echo img('tableExport/png.png'); ?>  PNG
            </a>
          </li>
          <li>
            <a onClick ="doExport({type:'pdf',ignoreColumn:'[5,6,7]'});" href="#">
               <img src="{% static "img/tableExport/pdf.png" %}" /> PDF
            </a>
          </li>
      </ul>

  </span>
</div>

	<table id="myTable"  class="table table-striped cell-border table-responsive">
      <thead>
         <tr>
             <th> First Name</th>
             <th> Middle Name</th>
             <th> Last Name</th>
             <th> Email</th>
             <th> Tel1</th>
             <th> Tel2</th>
             <th colspan="3">Actions</th>
         </tr>
      </thead>
          <tbody>
            {% for contact in contacts %}              
                <tr>
                    <td> {{contact.firstname}} </td>
                    <td> {{contact.middlename}} </td>
                    <td> {{contact.lastname}} </td>
                    <td> {{contact.email}} </td>
                    <td> {{contact.tel1}} </td>
                    <td> {{contact.tel2}} </td>
                    <td><a href="{% url 'contacts:sendmail' contact.id %}" class="glyphicon glyphicon-envelope"> Send Email</a></td>
                    <td><a href="{% url 'contacts:edit' contact.id %}" class="glyphicon glyphicon-edit"> Edit</a></td>
                    <td><a href="{% url 'contacts:delete' contact.id %}" class="glyphicon glyphicon-trash"> Delete</a></td>                 
                </tr>
            {% endfor %}
          </tbody>
      <tfoot>
         <tr>
             <th> First Name</th>
             <th> Middle Name</th>
             <th> Last Name</th>
             <th> Email</th>
             <th> Tel1</th>
             <th> Tel2</th>
             <th colspan="3">Actions</th>
         </tr>
      </tfoot>
    </table>

</div>
{% endblock %}


{%block extra_scripts %}
<script type="text/javascript" src="{% static 'js/dataTables/jquery.dataTables.js' %}" ></script>
<!--table Export-->
<script type="text/javascript" src="{% static 'js/tableExport/tableExport.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/tableExport/libs/FileSaver/FileSaver.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/tableExport/libs/html2canvas/html2canvas.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/tableExport/libs/jsPDF/jspdf.min.js' %}" ></script>

	<!--function to do export-->
	<script>
		function doExport (params){
			var options = {tableName: 'All Contacts',
				worksheetName: 'All Contacts'};
			$.extend(true, options, params);
			$('#myTable').tableExport(options);
		}
	</script>
{% endblock %}

app_contacts/templates/app_contacts/rptAllContacts.html
{% load static %}

<!DOCTYPE HTML >
<html>
<head>
	<title>Report</title>  
</head>

<body>
    <table>
      <tbody>                 
        <tr>
            <td style="width:150px;"> <img style="height:70px;width:70px" src="{{ domain }}/static/img/sword.png" /> </td>
            <td style="text-align: center"> <span style="font-weight:bold;font-size: 20px;">ALL CONTACTS REPORT</span> </td>
            <td style="width:150px"> <p>Printed on : {{today}}</p> </td>
        </tr>
      </tbody>
    </table>
<hr>

<div>
	<table>
      <thead>
         <tr>
             <th style="text-align: left;width:120px"> First Name</th>
             <th style="text-align: left;width:120px"> Middle Name</th>
             <th style="text-align: left;width:120px"> Last Name</th>
             <th style="text-align: left;width:200px"> Email</th>
             <th style="text-align: left;width:120px"> Tel1</th>
             <th style="text-align: left;width:120px"> Tel2</th>
         </tr>
      </thead>
          <tbody>
            {% for contact in contacts %}              
                <tr>
                    <td> {{contact.firstname}} </td>
                    <td> {{contact.middlename}} </td>
                    <td> {{contact.lastname}} </td>
                    <td> {{contact.email}} </td>
                    <td> {{contact.tel1}} </td>
                    <td> {{contact.tel2}} </td>
                </tr>
            {% endfor %}
          </tbody>
    </table>
</div>

</body>
</html>

app_contacts/templates/app_contacts/sendmail.html
{% extends "layout/master.html" %}
{% load static %}
{% block title %}Send Mail{% endblock %}

{% block content %}

<div class="col-sm-6">

<h3>Send EMail to {{contact}}</h3>
<i>(Note. All fields tagged with a star symbol(*) are strictly required)</i>
<hr/>

    <!--Show notification/error messages here -->
	{% if messages %}
		{% include "layout/messages.html" %}
	{% endif %}


<form class="row" method="post" action="{% url 'contacts:sendmail' contact.id %}">
{% csrf_token %}

	<div>	

		<!--Recipient-->
		<div class="form-group">
			<label for="recipient">Recipient*</label>
			<input readonly type="text" name="recipient" maxlength="30" class="form-control" value="{{ contact.email }}"  >
			<small class="alert-danger">{{ emailform.recipient.errors }}</small>
		</div>

		<!--Subject-->
		<div class="form-group">
			<label for="subject">Subject*</label>
			<input type="text" name="subject"  maxlength="30" class="form-control" value="{{ emailform.subject.value }}"  >
			<small class="alert-danger">{{ emailform.subject.errors }}</small>
		</div>


		<!--Message-->
		<div class="form-group">
			<label for="message">Message*</label>
			<textarea type="text" name="message"  maxlength="1000" class="form-control" >{{ emailform.message.value }}</textarea>
			<small class="alert-danger">{{ emailform.message.errors }}</small>
		</div>



	</div>


	<span class="clearfix"></span>
    <hr />
    <a class="btn btn-sm btn-default" href="{% url 'contacts:index' %}">Back</a>
    <button class="btn btn-sm btn-primary" type="submit">Send Mail</button>

</form>


</div>
{% endblock %}