app_api/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('all/<str:response_type>', views.contacts, name='contacts'),
	path('directions/', views.directions, name='directions'),
	path('contact_list/', views.ContactList.as_view()),
	path('contact_detail/<int:pk>', views.ContactDetail.as_view()),
	path('user_list/', views.UserList.as_view())
]

app_contacts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'contacts'
urlpatterns = [
	path('index/', login_required( views.IndexView.as_view() ), name='index'),
	path('add/', login_required( views.AddView.as_view() ), name='add'),
	path('edit/<int:pk>', login_required(views.EditView.as_view() ), name='edit'),
	path('delete/<int:pk>', login_required(views.DeleteView.as_view() ), name='delete'),
	path('sendmail/<int:pk>', login_required( views.EmailView.as_view() ), name='sendmail'),
	path('report/', login_required( views.ReportView ), name='report'),
]

app_homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
	path('', views.IndexView.as_view(), name='default'),
	path('index', views.IndexView.as_view(), name='index'),
	path('about', views.AboutView.as_view(), name='about'),
	path('contact', views.ContactView.as_view(), name='contact')
]

app_users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'users'
urlpatterns = [
	path('login/', views.LoginView.as_view(), name='login'),
	path('logout/', views.LogoutView.as_view(), name='logout'),
	path('registration/', views.RegistrationView.as_view(), name='registration'),
	path('manage/', login_required( views.ManageView.as_view() ), name='manage'),
	path('manage_personal_details/', login_required( views.ManagePersonalDetailsView.as_view() ), name='manage_personal_details'),
	path('change_user_password/', login_required( views.ChangeUserPasswordView.as_view() ), name='change_user_password'),
]

project/urls.py
from django.urls import include,path, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from rest_framework import routers
from app_api import views 

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'usersapi', views.UserViewSet)
router.register(r'contactsapi', views.ContactViewSet)

#handler404 = 'app_homepage.views.showError404'
#handler500 = 'app_homepage.views.showError500'

urlpatterns = [
    path('api/', include(router.urls)),   
    path('api/', include('app_api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('home/', include('app_homepage.urls')),
    path('users/', include('app_users.urls')),
    path('captcha/', include('captcha.urls')), 
    path('contacts/', include('app_contacts.urls')),
    path('password_reset_recover/', include('password_reset.urls')),  
    path('geodjango/', include('app_geodjango.urls')),
    path('tasks/', include('app_tasks.urls')),
    path('chat/', include('app_chat.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^.*', TemplateView.as_view(template_name='react.html')),
    
] 

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/layout/dialog.html
{% extends "layout/master.html" %}
{% load static %}
{% block title %}Dialog{% endblock %}

{% block content %}
<div align="center">
    <div class="alert alert-success" role="alert">
        <h4><strong>{{dialog_title}}</strong></h4>
        <br><br>

        <p>{{dialog_msg}}</p>
        <br>

           <!-- Yes or No selection -->
            <form class="row" method="post" action="{% url action_url args %}">
            {% csrf_token %}

                   <select name = "option" >
                        <option selected value = "no"> No </option>
                        <option value = "yes"> Yes </option>
                   </select>

                   &nbsp;&nbsp;&nbsp;

                  <input class = "btn btn-sm btn-primary" type = "submit" name = "submit" value = "Submit" >
            </form>
     </div>
</div>
{% endblock %}

templates/layout/error404.html
<h2>Custom error 404 page</h2>

templates/layout/error500.html
<h2>Custom error 500 page</h2>

templates/layout/logout.html
<div id="login">
	<h2>Logout</h2>
	
	<div class="box">
			You have been successfully logged out!
	</div>
</div>

templates/layout/master.html
{% load static %}

<!DOCTYPE HTML >
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name ="viewport" content="width=device-width, initial scale=1.0">
		<title>{% block title %}Homepage{% endblock %}</title>

		<!-- bootstrap -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.css' %}" />

		{% block extra_styles %}{% endblock %}

		<!--site css-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/tablet_and_up.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/desktop_and_up.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/large_desktops_and_up.css' %}" />
</head>
	
	<body>

		<!-- Fixed navbar -->
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'homepage:index' %}">
						<img style="display:inline;height:40px;width:40px" src="{% static 'img/sword.png' %}" alt="BrandName" /> DjangoBlade
					</a>
				</div>

				<!-- here is the main navigation links -->
				<div class="navbar-collapse collapse navbar-right">
					<ul class="nav navbar-nav">					
						<li class="active"> <a href="{% url 'homepage:index' %}">Home</a></li>
						{% if not user.is_authenticated %}
							<li><a style='border-radius:20px' href="{% url 'users:login' %}">Login</a></li>
							<li><a href="{% url 'users:registration' %}">Register</a></li>
						{% endif %}
						<li><a href="{% url 'homepage:about' %}">About Us</a></li>
						<li><a href="{% url 'homepage:contact' %}">Contact Us</a></li>


						<!--Public Menu-->
						{% if user.is_authenticated %}
							<li class="dropdown">								
								<li><a href="{% url 'contacts:index' %}">My Contacts</a></li>							
							</li>
						{% endif %}
					

						<!--Admin Dashboard-->
						{% if user.is_superuser %}
							<li><a class="nav-anchor dropdown-toggle" data-toggle="dropdown" href="">Dashboard</a></li>
						{% endif %}
		

						<!--Account Management and Logout-->
						{% if user.is_authenticated %}
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#"> <icon class="fa fa-user"></icon> {{user.username}} <b class="caret"></b> </a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="{% url 'users:manage' %}">My Account</a></li>
									<li><a href="{% url 'users:logout' %}">Logout</a></li>		
								</ul>
							</li>
						{% endif %}



					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<section style="{% if not logged_in %} margin-top:60px {% else %} margin-top:0 {% endif %}" >
			<div style="padding:0 20px">

        		{% block content %}{% endblock %}

			</div>
		</section>

		<!--popover content-->
		<div class="row" id="AccountPopoverContent">
				<div class="row">
					<div id="main-photo-div" class="col-sm-4">

						{% if unique_photo_filename %}
							<img alt="No Photo" id="acctphoto" class="img-responsive" 
							src="{% static "img/uploads/%s" % {{unique_photo_filename}} %}">
						{% else %}
							<img alt="No Photo" id="acctphoto" class="img-responsive" 
							src="{% static "app_users/img/usericon.svg" %}">	
						{% endif %}

					</div>

					<br class="hidden-lg" />
					<div id="my-account-div" class="col-sm-10 col-md-10 col-lg-5">
						<p> <b>{{username}}</b></p>
						<p>{{email}}</p>
						<a href="">My Account</a>
	
					</div>
				</div>

				<div>
					<a class="btn btn-sm btn-warning logout-btn" href=""><span class="glyphicon glyphicon-user"></span> Logout</a>
				</div>
		</div>

	<!--For responsive testing purposes-->
<!--	<div class="visible-xs"> now in xs</div>-->
<!--	<div class="visible-sm"> now in sm</div>-->
<!--	<div class="visible-md"> now in md</div>-->
<!--	<div class="visible-lg"> now in lg</div>-->

	<script type="text/javascript" src="{% static 'js/jquery-1.11.1.js' %}" ></script>	
	<script type="text/javascript" src="{% static 'js/bootstrap/bootstrap.js' %}" ></script>

	<!--site script-->
	<script type="text/javascript" src="{% static 'js/site.js' %}" ></script>

	{% block extra_scripts %}{% endblock %}

	</body>
</html>

templates/layout/messages.html
{% if messages %}
        
    {% for message in messages %}

        {% if message.tags == 'success' %} 
       
            <!--Show success message -->
            <div style="margin:5px 0;" class="alert alert-success alert-dismissible" role="alert" >
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <p><b> {{message}} </b></p>
            </div>


        {% elif message.tags == 'info' %} 

        <!--Show info message -->
        <div style="margin:5px 0;" class="alert alert-info alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
            </button>
            <p><b> {{message}} </b></p>
        </div>

        {% elif message.tags == 'warning' %} 

        <!--Show warning message -->
        <div style="margin:5px 0;" class="alert alert-warning alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
            </button>
            <p><b> {{message}} </b></p>
        </div>

        {% elif message.tags == 'error' %} 

        <!--Show error message -->
        <div style="margin:5px 0;" class="alert alert-danger alert-dismissible" role="alert" >
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
            </button>
            <p><b> {{message}} </b></p>
        </div>
        
        {% endif %}
        
    {% endfor %}
       
{% endif %}